"""Exercise 43 Basic Object oriented analysis and design"""

# READ THIS CHAPTER AGAIN
# READ THIS CHAPTER AGAIN
# READ THIS CHAPTER AGAIN
# READ THIS CHAPTER AGAIN
# READ THIS CHAPTER AGAIN
# READ THIS CHAPTER AGAIN
